server: passenger
port: 80
uri_path: "/cas"
bind_address: 0.0.0.0
database:
  pool: 10
  adapter: mysql2
  database: navionics_production
  username: root
  password: an12345678
  host: productiondbus-vpc2.cak6uco0ge8w.us-east-1.rds.amazonaws.com
  reconnect: true
authenticator:
  class: CASServer::Authenticators::SQLEncrypted
  database:
    adapter: mysql2
    database: navionics_production
    username: root
    password: an12345678
    host: productiondbus-vpc2.cak6uco0ge8w.us-east-1.rds.amazonaws.com
  user_table: users
  username_column: email
  password: encrypted_password
  encrypt_function: user.encrypted_password == Digest::SHA1.hexdigest("--#{user.salt}--#{@password}--")
  extra_attributes: token, nickname
theme: navionics
organization: Navionics
infoline:
custom_views: lib/casserver/navionics_views
log:
  file: "/var/log/casserver.log"
  level: INFO
db_log:
  file: "/var/log/casserver_db.log"
